-- Table: public.groups
DROP TABLE public.groups;

CREATE TABLE public.groups
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    permission text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.groups
    OWNER to postgres;



-- Add values to groups table
INSERT INTO public.groups(
	name, permission)
	VALUES ('read', 'READ'),('write', 'WRITE'),('delete', 'DELETE');



SELECT * FROM public.groups
ORDER BY id ASC


-- Table: public.user_group

-- DROP TABLE public.user_group;


CREATE TABLE public.user_group
(
    group_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT group_id FOREIGN KEY (group_id)
        REFERENCES public.groups (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT user_id FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT user_group_pkey PRIMARY KEY (group_id, user_id)
)

TABLESPACE pg_default;

ALTER TABLE public.user_group
    OWNER to postgres;
