-- Table: public.users
DROP TABLE public.users;

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    age integer NOT NULL,
    "isDeleted" boolean,
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;


INSERT INTO public.users(
	login, password, age, "isDeleted")
	VALUES ('John', 'Pass2', 10, null),('Khan', 'Perss3', 23, null),('Johan', 'Pass3', 65, null), ('Jonny', 'Pass4', 94, null);



SELECT * FROM public.users
ORDER BY id ASC
